spring.application.name=Clewa
spring.datasource.url=jdbc:postgresql://localhost:5433/clewa
spring.datasource.username=clewa
spring.datasource.password=clewa123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true